"""Making password_hash not nullable

Revision ID: a427652cd6d2
Revises: dc8b2dda95d4
Create Date: 2019-09-22 18:19:51.105782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a427652cd6d2'
down_revision = 'dc8b2dda95d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masterclass', sa.Column('masterclass_content_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'masterclass', type_='foreignkey')
    op.create_foreign_key(None, 'masterclass', 'masterclass_content', ['masterclass_content_id'], ['id'])
    op.drop_column('masterclass', 'masterclass_id')
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.add_column('masterclass', sa.Column('masterclass_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'masterclass', type_='foreignkey')
    op.create_foreign_key(None, 'masterclass', 'masterclass_content', ['masterclass_id'], ['id'])
    op.drop_column('masterclass', 'masterclass_content_id')
    # ### end Alembic commands ###
