"""Make max_attendees field not nullable

Revision ID: c5ad5402448d
Revises: 5315105a9a63
Create Date: 2020-01-15 17:57:40.177497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ad5402448d'
down_revision = '5315105a9a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('masterclass', 'max_attendees',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('masterclass', 'max_attendees',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
