"""masterclass content, location, masterclass and masterclass attendee tables

Revision ID: dc8b2dda95d4
Revises: e67044e1361d
Create Date: 2019-08-28 22:27:36.937431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8b2dda95d4'
down_revision = 'e67044e1361d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=50), nullable=True),
    sa.Column('street_number', sa.String(length=10), nullable=True),
    sa.Column('street_name', sa.String(length=100), nullable=True),
    sa.Column('town_or_city', sa.String(length=50), nullable=True),
    sa.Column('postcode', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_building'), 'location', ['building'], unique=False)
    op.create_index(op.f('ix_location_postcode'), 'location', ['postcode'], unique=False)
    op.create_index(op.f('ix_location_street_name'), 'location', ['street_name'], unique=False)
    op.create_index(op.f('ix_location_town_or_city'), 'location', ['town_or_city'], unique=False)
    op.create_table('masterclass_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masterclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('masterclass_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['masterclass_id'], ['masterclass_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masterclass_timestamp'), 'masterclass', ['timestamp'], unique=False)
    op.create_table('masterclass_attendee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=True),
    sa.Column('masterclass_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['masterclass_id'], ['masterclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('masterclass_attendee')
    op.drop_index(op.f('ix_masterclass_timestamp'), table_name='masterclass')
    op.drop_table('masterclass')
    op.drop_table('masterclass_content')
    op.drop_index(op.f('ix_location_town_or_city'), table_name='location')
    op.drop_index(op.f('ix_location_street_name'), table_name='location')
    op.drop_index(op.f('ix_location_postcode'), table_name='location')
    op.drop_index(op.f('ix_location_building'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
